release(gitforwindows.org): better failure reports of `git` invocations
When trying to update the site to reflect that Git for Windows v2.49.0
was released, the workflow failed with:

  [...]
  Pushing updates to git-for-windows/git-for-windows.github.io
  Cloning into 'git-for-windows.github.io'...
  Reset branch 'main'
  Auto-detected version 2.49.0 (Mon, 17 Mar 2025 09:40:38 UTC)
  Error: git commit -a -s -m New Git for Windows version failed with status 1
      at callProg (/home/runner/work/git-for-windows-automation/git-for-windows-automation/repository-updates.js:8:33)
      at callGit (/home/runner/work/git-for-windows-automation/git-for-windows-automation/repository-updates.js:13:10)
      at pushRepositoryUpdate (/home/runner/work/git-for-windows-automation/git-for-windows-automation/repository-updates.js:124:5)
      at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35424:16), <anonymous>:4:7)
      at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35425:12)
      at main (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35522:26)
      at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:35497:1
      at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:35553:3
      at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35556:12)
      at Module._compile (node:internal/modules/cjs/loader:1469:14)
  Error: Unhandled error: Error: git commit -a -s -m New Git for Windows version failed with status 1
  [...]

This is not helpful. The (hidden) `stdout` wanted to say this:

  On branch main
  Your branch is up to date with 'origin/main'.

  nothing to commit, working tree clean

Let's unhide that kind of errors.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>