mergeBundle(): use the absolute bundle path
When merging a bundle in a repository that specifically lives in a
different worktree, we need to turn any relative bundle path into an
absolute one. Otherwise we're greeted with an error message like this
one:

  Error: git fetch pkg-x86_64/MINGW-packages.bundle main: failed with status 128

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>